### ISSUE TITLE
tests error

### ISSUE THREAD

**Issue by guokai8** [tomlof/OnPLS#1]
I download the package and run the test. it reports

```
FAIL: test_comparison_to_nPLS (tests.test_OnPLS.TestOnPLS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bioguo/Desktop/OnPLS/tests/test_OnPLS.py", line 86, in test_comparison_to_nPLS
    assert(np.linalg.norm(Xhat[0] - np.dot(t, p3.T)) < 5e-14)
AssertionError
```

**Comment by tomlof** [comment]
I've made the bound slightly less tight. Could you try now? What version of Python are you using, and what OS? I've observed some minor differences coming from random number generation on different systems.

**Comment by guokai8** [comment]
My OS is OSX10.11,python version is 2.7.9

**Comment by tomlof** [comment]
Ok, then something is broken. I will see if I can get a hold of a computer with OSX. Or perhaps you could try and see how it breaks?

I have currently only tested it on Windows 7 with Python 2.7.11 and on Ubuntu 14.04 with Python 2.7.6 and Python 3.4.3.

If you have access to another computer you could test on that one for now.

Also, I know there were some issues with the version of Python that was shipped with OSX some years ago. Perhaps that is still an issue? If so, you could try to use the official OSX build of Python.

**Comment by tomlof** [comment]
I've been able to run the tests on OSX 10.8.5 and Python 2.7.5, and they run fine, without any problems.

Have you been able to see if you can figure out why it crashes? Feel free to send a pull request if you find a fix for the error.

I might be able to run it on Sierra, and will try that approach as soon as I can.

**Comment by guokai8** [comment]
I will try to figure out why it crash in my computer.

> 在 2016年10月5日，20:34，Tommy Löfstedt notifications@github.com 写道：
> 
> crashes

**Comment by guokai8** [comment]
Hi,
Could you send me a simple manual for the program, I will try follow your manual maybe it will help me to figure out why it crashed.Thanks!
Best,
Kai Guo 

> 在 2016年10月5日，20:34，Tommy Löfstedt notifications@github.com 写道：
> 
> without

**Comment by tomlof** [comment]
I've added a quick start guide to the Readme file on the package's first page. Perhaps it could help you?

**Comment by guokai8** [comment]
Sure! I will follow the manual, Thanks!
