### ISSUE TITLE
OnPLS new version methods

### ISSUE THREAD

**Issue by wenjun1992** [tomlof/OnPLS#4]
Dear Prof.Tommy,
I was so excited to read your OnPLS paper and methods and I really want to use your package to do data analysis because this methods is very suitable for my data and study. But I have a question, if you have new version package for the methods, because it is hard to use python 3.4.3 for me. Thanks very much.

**Comment by tomlof** [comment]
I've fixed some use of deprecated Numpy functions. All tests ran now in Python 10. Please let me know if there are any other issues. Contributions are welcome!

**Comment by wenjun1992** [comment]
> I've fixed some use of deprecated Numpy functions. All tests ran now in Python 10. Please let me know if there are any other issues. Contributions are welcome!

i

**Comment by wenjun1992** [comment]
I thank you very much for your update and reply. Thanks very much!!!
